/*
  sigdemo0.c
  jbs

  displays "Hanging out", endlessly.
  Purpose is to for us to interupt it with a signal, say SIGINT
  generated by ^C.
 */

#include <stdio.h>  // puts
#include <unistd.h> // sleep

int main(void) {
    while(1) {
        puts("Hanging out");
        sleep(1);
    }
}
